

CREATE TABLE IF NOT EXISTS ticket_inventory (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    inventory_identifier VARCHAR(255) NOT NULL UNIQUE,
    event_id VARCHAR(255) NOT NULL,
    ticket_type VARCHAR(255) NOT NULL,
    total_tickets INT NOT NULL,
    available_tickets INT NOT NULL
);